import * as React from 'react';
import { createStyles, Theme, makeStyles } from '@material-ui/core/styles';
import Typography from '@material-ui/core/Typography';
import Image from 'next/image';
import { useStores } from '../../stores/StoreProvider';
import { observer } from 'mobx-react';

const useStyles = makeStyles((theme) => ({
  root:{ 
    backgroundColor: 'white'
  },
  clusterGroup:{ 
    padding: theme.spacing(4,0,2)
  },
  indivData:{
    textAlign: 'center',
    //alignSelf: 'center',
  },
  text:{
    padding:theme.spacing(3,0,3)
  },
  iconGrid:{
    margin: theme.spacing(6,0,0)
  }
}));

const LearningPathInfo: React.FC = () => {

  const { uiState, appStore } = useStores(); 
  const classes = useStyles();

  return (
    <div className={classes.root}>
        <Typography variant="h5">What are Learning Paths?</Typography>
        <br/>
        <Typography>Each learning path is a recommended <b>sequence of exercises</b> that trainers can use to teach students a certain concept.</Typography>
        <br/>
        <div style={{textAlign:'center'}}>
            <Image src="/learningPath.jpg" height='190' width='1200'/>
            <br/>
            <Typography variant="caption" style={{textDecoration: 'underline'}}>Example of Learning Path (generated by performance)</Typography>
        </div>
        <br/>
        <br/>
        <Typography>Ther are 3 metrics to rank the learning paths namely <b>by popularity</b>, <b>by average performance</b> or simply <b>by the length of the learning path</b>. For each metric, the top 5 paths that are generated will be displayed.</Typography>
    </div>
  );
};

export default observer(LearningPathInfo); 