export const studentListData = [
    {
        "uuid": "7",
        "problems_attempted": "23",
        "exercises_attempted": "3",
        "avg_time_per_exercise": "28.56521739",
        "avg_accuracy": "0.913043478",
        "no_upgrades": "2",
        "no_downgrades": "0",
        "avg_hint_per_attempt": "0",
        "avg_time_btw_problem": "200",
        "id": "7",
        "name": "Paul Franco",
        "gender": "male",
        "points": "7503",
        "badges_cnt": "0",
        "first_login_date_TW": "2019-01-24",
        "user_grade": "2",
        "user_city": "kh",
        "is_self_coach": "False",
        "belongs_to_class_cnt": "1",
        "has_class_cnt": "0",
        "has_teacher_cnt": "1",
        "has_student_cnt": "0"
    },
    {
        "uuid": "8",
        "problems_attempted": "23",
        "exercises_attempted": "3",
        "avg_time_per_exercise": "28.56521739",
        "avg_accuracy": "0.913043478",
        "no_upgrades": "2",
        "no_downgrades": "0",
        "avg_hint_per_attempt": "0",
        "avg_time_btw_problem": "200",
        "id": "7",
        "name": "Kelly James",
        "gender": "male",
        "points": "7503",
        "badges_cnt": "0",
        "first_login_date_TW": "2019-01-24",
        "user_grade": "2",
        "user_city": "kh",
        "is_self_coach": "False",
        "belongs_to_class_cnt": "1",
        "has_class_cnt": "0",
        "has_teacher_cnt": "1",
        "has_student_cnt": "0"
    },
    {
        "uuid": "9",
        "problems_attempted": "23",
        "exercises_attempted": "3",
        "avg_time_per_exercise": "28.56521739",
        "avg_accuracy": "0.913043478",
        "no_upgrades": "2",
        "no_downgrades": "0",
        "avg_hint_per_attempt": "0",
        "avg_time_btw_problem": "200",
        "id": "7",
        "name": "David Greenfield",
        "gender": "male",
        "points": "7503",
        "badges_cnt": "0",
        "first_login_date_TW": "2019-01-24",
        "user_grade": "2",
        "user_city": "kh",
        "is_self_coach": "False",
        "belongs_to_class_cnt": "1",
        "has_class_cnt": "0",
        "has_teacher_cnt": "1",
        "has_student_cnt": "0"
    },
    {
        "uuid": "7",
        "problems_attempted": "23",
        "exercises_attempted": "3",
        "avg_time_per_exercise": "28.56521739",
        "avg_accuracy": "0.913043478",
        "no_upgrades": "2",
        "no_downgrades": "0",
        "avg_hint_per_attempt": "0",
        "avg_time_btw_problem": "200",
        "id": "7",
        "name": "Paul Franco",
        "gender": "male",
        "points": "7503",
        "badges_cnt": "0",
        "first_login_date_TW": "2019-01-24",
        "user_grade": "2",
        "user_city": "kh",
        "is_self_coach": "False",
        "belongs_to_class_cnt": "1",
        "has_class_cnt": "0",
        "has_teacher_cnt": "1",
        "has_student_cnt": "0"
    },
]